import {stoneArt, STONE_DETAILS} from './stone-art.js';
import {CARGO_SPECS,DECK,footprint,occupiedCells,placementProblem,suggestPlacement} from './cargo-packing.js';
import {buyCargo,buyOrder,placeCargo,unloadCargo,harborStats,dispatchProblem,dispatchCargo,arriveCargo,undoVoyage,beginExpansionBuild,VOYAGE_MS} from './harbor-game.js';
import {confirmOrder} from './journey-game.js';
import {createHarborWorld} from './harbor-world.js';
import {createOrderReference} from './harbor-reference.js';
let arrivalTimer,timerVoyage,world,api,reference;
export function clearHarborTimer(){clearTimeout(arrivalTimer);arrivalTimer=null;timerVoyage=null;}
const names={brick:'Flat bricks',edge:'Edge stones',corner:'Corner stones',cap:'Capstone'};
const symbols={brick:'B',edge:'E',corner:'C',cap:'▲'};
const clean=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function footprintArt(type,rotation=0){const cells=footprint(type,rotation),w=Math.max(...cells.map(c=>c[0]))+1,h=Math.max(...cells.map(c=>c[1]))+1;return `<svg class="sled-icon" viewBox="0 0 ${w*12+2} ${h*12+2}" aria-hidden="true">${cells.map(([c,r])=>`<rect x="${c*12+1}" y="${r*12+1}" width="11" height="11" rx="1.5"/><path d="M${c*12+4} ${r*12+4}h5"/>`).join('')}<circle cx="4" cy="4" r="1.4" fill="currentColor"/></svg>`;}
function referenceHTML(level){return `<div class="order-reference"><div class="mini-blueprints">${level.dims.map((n,y)=>{const owned=level.journeyRole==='expand'&&y>0;return `<div class="reference-layer ${owned?'owned':''}"><span>L${y+1} · ${n}×${n}</span><div style="grid-template-columns:repeat(${n},1fr)">${level.blueprint.filter(b=>b.y===y).map(b=>`<i class="ref-${b.type}" title="${STONE_DETAILS[b.type].label}">${symbols[b.type]}</i>`).join('')}</div><small>${owned?'Already built':n*n+(n===1?' stone':' stones')}</small></div>`;}).join('')}</div><p>${level.journeyRole==='expand'?'Keep your 14 stones. Order only the new 4 × 4 foundation.':'9 foundation stones + 4 upper corners + 1 cap = 14 stones.'}</p></div>`;}
function orderHTML(state,level){const q=level.requiredNewQuantities,done=state.stage==='complete',cost=Object.entries(q).reduce((n,[t,c])=>n+c*level.prices[t],0);return `<div class="harbor-heading"><span class="eyebrow">AT THE QUARRY MARKET · ${level.journeyRole==='expand'?'A LARGER AMBITION':'BEFORE THE FIRST STONE'}</span><h2>${level.journeyRole==='expand'?'Make room for<br>one more layer.':'A little plan.<br>A lasting wonder.'}</h2><p>${level.journeyRole==='expand'?'Your three layers become the top of a four-layer pyramid. The new foundation needs its own shipment.':'Study the model in your shopping list.<br>Browse the packed stones at the quarry.'}</p></div>
  <section class="order-paper"><span class="eyebrow">${done?'YOUR ORDER IS READY':'01 / YOUR SHOPPING LIST'}</span><h3>${level.journeyRole==='expand'?'16 new foundation stones':'A three-layer pyramid'}</h3><div id="order-model-slot"></div><details class="order-layers"><summary>Layer-by-layer count · ${level.dims.reduce((n,d)=>n+d*d,0)} stones</summary>${referenceHTML(level)}</details>
  <div class="reference-key">${level.types.map(t=>`<span><i class="ref-${t}">${symbols[t]}</i>${STONE_DETAILS[t].label}</span>`).join('')}</div>
  <div class="shopping-rows">${level.types.map(type=>`<label class="shopping-row"><span class="order-stone">${stoneArt(type)}</span><span><strong>${names[type]}</strong><small>Need ${q[type]||0} · ${level.prices[type]} coins each</small></span><input data-shopping="${type}" aria-label="Shopping list ${names[type]}" type="number" inputmode="numeric" min="0" max="30" value="${clean(state.estimates[type])}" ${done?'disabled':''}/></label>`).join('')}</div>
  <div class="order-budget"><span>Stone ${cost}<small>+ reserve 12 for shipping</small></span><strong>${level.budget}<small>contract coins</small></strong></div>
  ${done?'<div class="order-approved">✓ Shopping list checked · 20 coins earned</div><button id="order-next" class="primary full">Visit the quarry →</button>':'<button id="confirm-order" class="primary full">Confirm my shopping list →</button><button id="reference-counts" class="text-button">Copy the reference counts</button>'}
  <p class="fineprint">The model is a reference. Your construction starts after delivery.</p>
  </section><div class="harbor-scene-caption">Tap a market stack to study that stone · drag the scene to look around</div>${cameraHTML(false)}`;}
function cameraHTML(cargo=true){return `<div class="harbor-camera" aria-label="Harbor camera"><button id="harbor-home" aria-label="Reset harbor view">⌂</button><button id="market-view">Market</button>${cargo?'<button id="deck-view">Deck view</button>':''}<button id="harbor-zoom-in" aria-label="Zoom harbor in">+</button><button id="harbor-zoom-out" aria-label="Zoom harbor out">−</button></div>`;}
function balanceHTML(m){return `<div class="balance-target ${m.balanced?'balanced':''}" aria-label="${m.balanced?'Balanced':'Unbalanced'} in both directions"><span class="balance-safe"></span><i style="left:${50+Math.max(-1,Math.min(1,m.offsetX))*43}%;top:${50+Math.max(-1,Math.min(1,m.offsetZ))*43}%"></i><span class="axis-x"></span><span class="axis-z"></span></div>`;}
function deckMapHTML(state){const h=state.harbor;return `<div class="accessible-deck" role="group" aria-label="Accessible deck map, bow at top">${Array.from({length:20},(_,i)=>{const c=i%5,r=Math.floor(i/5),blocked=DECK.blocked.some(([x,z])=>x===c&&z===r),item=h.cargo.find(a=>a.status==='boat'&&occupiedCells(a).some(([x,z])=>x===c&&z===r));return `<button data-deck="${c},${r}" class="${blocked?'mast':''} ${item?'occupied '+item.type:''}" ${h.inTransit||blocked&&(!h.selected||placementProblem(h.cargo,h.cargo.find(a=>a.id===h.selected),c,r,h.rotation))?'disabled':''} aria-label="Deck ${String.fromCharCode(65+c)}${r+1}${blocked?', mast':item?', '+STONE_DETAILS[item.type].label:', empty'}">${blocked?'╋':item?symbols[item.type]:`${String.fromCharCode(65+c)}${r+1}`}</button>`;}).join('')}</div>`;}
function cargoHTML(state,level){const h=state.harbor,m=harborStats(state),sailing=!!h.inTransit,finished=h.finished||state.stage==='complete';const selected=h.cargo.find(c=>c.id===h.selected),market=h.cargo.filter(c=>c.status==='market'),cost=market.reduce((n,c)=>n+level.prices[c.type],0),problem=dispatchProblem(state,level);
  const title=sailing?'Downriver, to Giza.':finished?'Every stone, delivered.':level.journeyRole==='expand'?'A wider foundation.':'A river full of possibility.';
  const hasBought=h.cargo.some(c=>c.status!=='market');
  return `<div class="harbor-heading cargo-heading"><span class="eyebrow">THE QUARRY QUAY · ${level.journeyRole==='expand'?'EXPANSION SHIPMENT':'YOUR FIRST SHIPMENT'}</span><h2>${title}</h2><p>${sailing?'Your cargo travels with the barge. The next load waits at the quay.':finished?'The order is waiting at the building site.':hasBought?'Pick a packed stone from the market. Rotate its sled and fit it on the deck.':'Your shopping list is ready. Buy the stones, then pack the boat.'}</p></div>
  <section class="cargo-order ${h.showOrder?'expanded':''}" aria-label="Shipment order"><button id="toggle-cargo-order" class="cargo-order-heading" aria-expanded="${!!h.showOrder}"><span>THE SHIPPING ORDER <small>${m.delivered}/${h.cargo.length} delivered</small></span><strong>◉ ${state.money}</strong><i>⌄</i></button>
  <div class="cargo-order-body"><div class="manifest-labels"><span>Stone</span><span>Quay</span><span>Boat</span><span>Giza</span></div>${level.types.filter(t=>level.requiredNewQuantities[t]).map(type=>{const list=h.cargo.filter(c=>c.type===type),n=status=>list.filter(c=>c.status===status).length;return `<div class="manifest-row"><span>${stoneArt(type)}<b>${STONE_DETAILS[type].label}<small>Order ${list.length}</small></b></span><strong>${n('quay')}</strong><strong>${n('boat')+n('transit')}</strong><strong>${n('delivered')}</strong></div>`;}).join('')}
  ${market.length?`<button id="buy-order" class="gold full" ${sailing||cost>state.money?'disabled':''}>Buy ${hasBought?'remaining':'shopping list'} · ${cost} coins</button>`:''}
  <div class="freight-ledger"><span>Freight paid <b>${h.feesPaid} coins</b></span><span>Voyages <b>${state.trips} / aim for 3</b></span></div>
  <p class="fineprint">Budget covers four voyages. Three earns the Efficient Captain seal. Unpack and rearrange freely.</p>
  <div class="cargo-order-links"><button id="undo-voyage" ${!h.voyages.length||sailing||finished?'disabled':''}>Undo last voyage</button><button id="harbor-restart">Restart shipment</button></div>
  <details class="packing-rules"><summary>The boat’s rules</summary><p>5 × 4 deck. Two spaces belong to the mast. Sleds cannot overlap or hang over the side. At most 16 weight per voyage.</p><p>The balance dot must stay inside the central square. Distribute weight both left to right and bow to stern.</p><p>Sleds include protective space; these are transport shapes, not the dimensions of masonry.</p></details></div></section>
  ${sailing?`<div class="voyage-banner"><span class="eyebrow">VOYAGE ${h.inTransit.number} · ${h.inTransit.weight}/16 WEIGHT</span><strong>Quarry <span class="voyage-line">→</span> Giza</strong><button id="finish-voyage">Skip voyage animation</button></div>`:finished?`<section class="harbor-complete"><span class="eyebrow">${state.trips<=3?'✦ EFFICIENT CAPTAIN':'✓ SHIPMENT COMPLETE'}</span><h3>${h.cargo.length} stones.<br>Ready for your hands.</h3><p>${state.trips} voyages · ${h.feesPaid} freight coins · ${state.money} left</p>${level.journeyRole==='cargo'?`<p class="shipping-wage">${h.earnedThisRun?'+25 earned coins · Spend them in Free Design':'Commission wage already earned'}</p>`:''}<button id="harbor-next" class="primary full">${level.journeyRole==='expand'?'Fit the wider foundation':'Build my three layers'} →</button></section>`:`
  <div class="cargo-controls"><div class="load-readout"><div class="load-weight"><span>HOLD WEIGHT</span><strong>${m.weight}<small> / ${DECK.capacity}</small></strong><div class="weight-track"><i class="${m.overweight?'danger':''}" style="width:${Math.min(100,m.weight/DECK.capacity*100)}%"></i></div><small>${m.tiles} of 18 usable spaces</small></div>${balanceHTML(m)}<div class="balance-copy"><span>TRIM & BALANCE</span><strong>${m.items?m.balanced?'Steady on both axes':'Shift the weight':'Ready to load'}</strong><small>Keep the dot in the square</small></div></div>
  <div class="cargo-guidance"><p id="cargo-placement-hint" role="status" aria-live="polite">${selected?`${STONE_DETAILS[selected.type].label} selected · ${CARGO_SPECS[selected.type].weight} weight · tap a deck space`:m.items?problem||'A steady load. Sail now, or fit one more sled.':'Tap a market stack or choose a stone below, then place its sled on the boat.'}</p><button id="sail-cargo" class="primary" ${problem?'disabled':''}>Sail · ${DECK.fee} coins →</button></div>
  <div class="cargo-tray" aria-label="Quarry cargo">${level.types.filter(t=>level.requiredNewQuantities[t]).map(type=>{const quay=h.cargo.filter(c=>c.type===type&&c.status==='quay'),unbought=h.cargo.filter(c=>c.type===type&&c.status==='market'),active=selected?.type===type;return `<button class="cargo-stock ${type} ${active?'active':''}" data-cargo-type="${type}" ${!quay.length&&!unbought.length?'disabled':''} aria-label="${quay.length?`Select ${STONE_DETAILS[type].label}, ${quay.length} at quay`:`Buy ${STONE_DETAILS[type].label}, ${level.prices[type]} coins`}" aria-pressed="${active}"><span class="cargo-stone-art">${stoneArt(type)}</span><span class="cargo-stock-text"><b>${STONE_DETAILS[type].label}</b><small>${quay.length?`${quay.length} at quay`:unbought.length?`Buy · ${level.prices[type]} coins`:'All aboard / delivered'}</small></span><span class="cargo-footprint">${footprintArt(type,active?h.rotation:0)}<small>${CARGO_SPECS[type].weight} wt</small></span></button>`;}).join('')}</div>
  <div class="packing-actions"><span class="selection-label">${selected?`${STONE_DETAILS[selected.type].label} · ${h.rotation}°`:'Padded sleds protect your stone'}</span><button id="rotate-cargo" ${!selected?'disabled':''}>↻ Rotate <kbd>R</kbd></button><button id="unload-cargo" ${selected?.status!=='boat'?'disabled':''}>To quay</button><button id="deselect-cargo" ${!selected?'disabled':''}>Orbit / cancel</button><button id="cargo-hint" ${!selected?'disabled':''}>Placement hint</button><button id="toggle-deck-map" aria-expanded="${!!h.showMap}">${h.showMap?'Close':'Open'} deck map</button></div>
  ${h.showMap?deckMapHTML(state):''}</div>`}
  ${cameraHTML()}<div class="harbor-scene-caption">${sailing?'A cargo journey on the Nile':'Drag water to orbit · scroll to zoom · R to rotate cargo'}</div>`;
}
export function renderHarbor(context){api=context;const{state,level,save,render,notice,next}=context;
  let host=document.getElementById('harbor-world');if(!host){document.getElementById('harbor-scene').innerHTML='<div id="harbor-world"></div><div id="harbor-hud"></div>';host=document.getElementById('harbor-world');}
  const order=state.stage==='order'||level.journeyRole==='order';document.getElementById('harbor-scene').dataset.phase=order?'order':'cargo';
  reference?.element.remove();
  document.getElementById('harbor-hud').innerHTML=order?orderHTML(state,level):cargoHTML(state,level);
  if(order){reference??=createOrderReference();document.getElementById('order-model-slot').append(reference.element);reference.sync(level);}
  const update=()=>{save();render();};
  const select=id=>{if(state.harbor.inTransit)return;const c=state.harbor.cargo.find(c=>c.id===id&&['boat','quay'].includes(c.status));if(!c)return;state.harbor.selected=id;state.harbor.rotation=c.rotation||0;update();};
  const place=(column,row)=>{const h=state.harbor,item=h.cargo.find(c=>c.id===h.selected);if(!item)return;const problem=placementProblem(h.cargo,item,column,row,h.rotation);if(problem){notice(problem);return;}if(placeCargo(state,item.id,column,row,h.rotation))update();};
  const rotate=()=>{if(!state.harbor?.selected||state.harbor.inTransit)return;state.harbor.rotation=(state.harbor.rotation+90)%360;update();};
  const deselect=()=>{if(state.harbor){state.harbor.selected=null;update();}};
  // Keep one canvas and one camera alive across every stock, rotation and placement update.
  if(!world){world=createHarborWorld(host,()=>api,{onSelect:id=>api.select(id),onMarket:type=>api.market(type,true),onPlace:(c,r)=>api.place(c,r),onDeselect:()=>api.deselect(),onHover:text=>{const e=document.getElementById('cargo-placement-hint');if(e)e.textContent=text;}});
    document.addEventListener('keydown',e=>{if(document.getElementById('harbor-scene').hidden||document.querySelector('.modal-shade')||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;if(e.key.toLowerCase()==='r'){e.preventDefault();api.rotate();}if(e.key==='Escape')api.deselect();});}
  const market=(type,fromScene=false)=>{
    if(order){const input=document.querySelector(`[data-shopping="${type}"]`);if(input){document.querySelectorAll('.shopping-row').forEach(e=>e.classList.remove('market-inspected'));input.closest('.shopping-row').classList.add('market-inspected');input.scrollIntoView({block:'nearest',behavior:'smooth'});input.focus({preventScroll:true});reference?.highlight(type);notice(`${names[type]} · ${CARGO_SPECS[type].weight} cargo weight · ${level.requiredNewQuantities[type]||0} needed. Add the count to your list.`);}return;}
    if(state.harbor.inTransit||state.harbor.finished)return;
    const item=state.harbor.cargo.find(c=>c.type===type&&c.status==='quay');
    if(item)select(item.id);else if(buyCargo(state,level,type))update();else return;
    if(fromScene||world.view==='market')world.home();
  };
  Object.assign(api,{select,place,rotate,deselect,market});world.sync();
  const bind=(id,fn)=>{const e=document.getElementById(id);if(e)e.onclick=fn;};
  bind('harbor-home',()=>world.home());bind('market-view',()=>{deselect();world.marketView();});bind('deck-view',()=>world.topView());bind('harbor-zoom-in',()=>world.zoom(.86));bind('harbor-zoom-out',()=>world.zoom(1.16));
  if(order){clearHarborTimer();document.querySelectorAll('[data-shopping]').forEach(e=>e.oninput=()=>{state.estimates[e.dataset.shopping]=e.value;save();});
    bind('reference-counts',()=>{for(const t of level.types)state.estimates[t]=String(level.requiredNewQuantities[t]||0);update();});
    bind('confirm-order',()=>{const problem=confirmOrder(state,level);if(problem)return notice(problem);save();if(level.journeyRole==='order')next();else render();});bind('order-next',next);return;
  }
  const h=state.harbor;
  document.querySelectorAll('[data-cargo-type]').forEach(e=>e.onclick=()=>market(e.dataset.cargoType));
  bind('buy-order',()=>{if(buyOrder(state,level))update();});bind('rotate-cargo',rotate);bind('deselect-cargo',deselect);bind('unload-cargo',()=>{if(unloadCargo(state,h.selected))update();});
  bind('cargo-hint',()=>{const item=h.cargo.find(c=>c.id===h.selected);if(!item)return;const hintCargo=h.cargo.filter(c=>c.id!==item.id);hintCargo.unshift({...item,status:'quay'});const suggestion=suggestPlacement(hintCargo,item.type);if(!suggestion)return notice('No open footprint fits. Move a sled or send a balanced load.');h.rotation=suggestion.rotation;update();world.preview(suggestion.column,suggestion.row);notice(`Try ${String.fromCharCode(65+suggestion.column)}${suggestion.row+1} at ${suggestion.rotation}°. The green footprint shows the space; you place it.`);});
  bind('toggle-deck-map',()=>{h.showMap=!h.showMap;update();});bind('toggle-cargo-order',()=>{h.showOrder=!h.showOrder;update();});
  document.querySelectorAll('[data-deck]').forEach(e=>e.onclick=()=>{const[c,r]=e.dataset.deck.split(',').map(Number);if(h.selected)place(c,r);else{const item=h.cargo.find(a=>a.status==='boat'&&occupiedCells(a).some(([x,z])=>x===c&&z===r));if(item)select(item.id);else notice('Select a sled from the quay first.');}});
  bind('sail-cargo',()=>{const result=dispatchCargo(state,level);if(result.problem)notice(result.problem);else update();});
  bind('undo-voyage',()=>{if(undoVoyage(state)){update();notice('Voyage undone. Its freight fee and cargo are back.');}});
  bind('harbor-restart',context.restart);
  bind('harbor-next',()=>{if(level.journeyRole==='expand'){beginExpansionBuild(state,level);save();render();context.onBuild?.();}else next();});
  const arrive=()=>{clearHarborTimer();if(arriveCargo(state,level))update();};bind('finish-voyage',arrive);
  if(h.inTransit&&timerVoyage!==h.inTransit){clearHarborTimer();timerVoyage=h.inTransit;arrivalTimer=setTimeout(arrive,Math.max(0,VOYAGE_MS-(Date.now()-h.inTransit.startedAt)));}
  else if(!h.inTransit)clearHarborTimer();
}
