import * as THREE from 'three';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
export const SITE_LORE={
 egypt:[
 ['quarry','The limestone quarry','Stone was cut from the Giza plateau. The cut faces, work bays and movements shown here are a reconstructed workshop, not a surveyed ancient plan.','AERA archaeology','https://aeraweb.org/projects/who-built-the-sphinx/'],
 ['tools','Copper and skilled hands','Researchers have studied copper-alloy tools from Fourth Dynasty Giza. Our small bench, mallets and cutting rhythm are illustrative.','Giza tool research','https://explorer.cuni.cz/publication/603949?lang=cs'],
 ['sledge','Pulling a stone together','Wooden sledges are known in ancient Egypt. This rope-hauling scene shows a plausible method; the exact pyramid construction routes remain debated.','UCL Egyptology','https://www.ucl.ac.uk/museums-static/digitalegypt/pyramids/how.html'],
 ['boat','A boatload from Tura','Merer’s surviving logbook records stone voyages to Khufu’s project. Our boat capacity and trip puzzle are simplified maths, not ancient measurements.','Merer papyrus translation','https://www.ifao.egnet.net/uploads/publications/divers/MIFAO136_ann_01.pdf'],
 ['supplies','Feeding the building team','Bread, beer, fish and meat were part of supplying Giza’s builders. This little food and shelter corner is a general reconstruction.','AERA food research','https://aeraweb.org/online-lecture-loaves-and-fishes/'],
 ['sphinx','Later at Giza: the Sphinx','Archaeological evidence links most of the Sphinx’s construction to Khafre, after Khufu. Turn on this separate later-Giza view to explore the landmark. It is not shown as a completed Khufu-era monument.','AERA construction sequence','https://aeraweb.org/why-sequence-is-important/']
 ],
 maya:[
 ['quarry','Working limestone','Maya builders worked local limestone. Our cutting ledges and stone-finishing benches are reconstructed work areas.','INAH Maya building materials','https://lugares.inah.gob.mx/es/taxonomy/term/56104?page=1'],
 ['carry','Human-powered carrying','This site uses people carrying manageable baskets and building material. The route is an illustration, not a documented transport system for El Castillo.','INAH Chichén research','https://gobiernodigital.inah.gob.mx/Transparencia/Archivos/1722273493.PDF'],
 ['plaster','Lime and plaster','Maya craftspeople made lime-based building materials. The mixing corner and heating area show that work in simplified form; regional kilns varied.','INAH lime research','https://revistas.inah.gob.mx/index.php/ventana/article/view/22435'],
 ['serpent','A serpent by the stairs','Serpent heads mark the north staircase of the outer temple. This carving bay is illustrative; earlier versions of the temple were different.','INAH El Castillo guide','https://arqueologia.inah.gob.mx/imagenes/publicaciones/publicaciones%2815245%29-2524.pdf'],
 ['layers','A building within a building','El Castillo was enlarged over earlier structures. Our small game has counted courses, while the real monument also has different historical building phases.','INAH investigation','https://www.inah.gob.mx/boletines/alistan-muografia-para-detectar-estructuras-interiores-en-el-castillo-de-chichen-itza']
 ],
 mesopotamia:[
 ['clay','The clay preparation yard','Ur’s builders made bricks from clay. The pit, molds and work layout are an illustrative reconstruction, not an excavated factory plan.','Penn Museum excavations','https://www.penn.museum/sites/journal/1356/'],
 ['dry','Shaping and drying','The game distinguishes sun-dried interior bricks from fired outer facing. These drying rows show a process, not an exact historical drying time.','Penn Museum Ur evidence','https://www.penn.museum/sites/journal/1297/'],
 ['facing','Fired outer bricks','Fired-clay bricks survive from Ur-Nammu’s building work. In the game, paying for the right outside material is part of the challenge.','British Museum brick','https://www.britishmuseum.org/collection/object/W_1919-1011-4675'],
 ['bitumen','Dark mortar seams','Builders at Ur used bitumen to bind brickwork. This modest work station illustrates the material without reproducing its historical handling process.','Penn Museum masonry report','https://www.penn.museum/sites/journal/1356/'],
 ['stamp','Marks in clay','Some bricks name Ur-Nammu in cuneiform. The marks on our teaching prop are decorative; they are not a translated ancient inscription.','British Museum stamped brick','https://www.britishmuseum.org/collection/object/W_1919-1011-4675']
 ]};
export function buildProps(parent,level,materials){const group=new THREE.Group();parent.add(group);const d=level.dims[0]/2,stone=materials.stone,earth=materials.earth;const wood=new THREE.MeshStandardMaterial({color:0x997443,roughness:.9}),cloth=new THREE.MeshStandardMaterial({color:0xf1e4c7,side:THREE.DoubleSide,roughness:1}),dark=new THREE.MeshStandardMaterial({color:0x4c4035,roughness:.8}),copper=new THREE.MeshStandardMaterial({color:0xb98456,roughness:.4,metalness:.45});let action=null,started=0,sledge,carrier,drying=[];
const mesh=(g,geo,mat,x=0,y=0,z=0)=>{const m=new THREE.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m;};const box=(g,x,y,z,w,h,l,mat=wood)=>mesh(g,new RoundedBoxGeometry(w,h,l,1,Math.min(.025,h/5)),mat,x,y,z);
const rope=(g,points,r=.012)=>mesh(g,new THREE.TubeGeometry(new THREE.CatmullRomCurve3(points.map(p=>new THREE.Vector3(...p))),16,r,5,false),wood);
function jar(g,x,z,scale=1){const pts=[[.055,0],[.12,.04],[.16,.17],[.12,.29],[.066,.34],[.066,.39]].map(p=>new THREE.Vector2(...p));const a=mesh(g,new THREE.LatheGeometry(pts,14),earth,x,0,z);a.scale.setScalar(scale);return a;}
function shelter(x,z){const g=new THREE.Group();g.position.set(x,0,z);group.add(g);for(const xx of[-.8,.8])for(const zz of[-.6,.6])mesh(g,new THREE.CylinderGeometry(.028,.038,1.15,7),wood,xx,.575,zz);const geo=new THREE.PlaneGeometry(1.8,1.45,6,5);const p=geo.attributes.position;for(let i=0;i<p.count;i++)p.setZ(i,-.13*(1-Math.pow(p.getX(i)/.9,2)));geo.computeVertexNormals();const roof=mesh(g,geo,cloth,0,1.15,0);roof.rotation.x=-Math.PI/2;jar(g,-.5,.2,.8);jar(g,.15,-.2,.65);return g;}
function quarry(){const g=new THREE.Group();g.position.set(-d-4,0,-d-.3);group.add(g);for(let i=0;i<3;i++)box(g,0,.16+i*.27,-i*.28,2.1-i*.32,.31,1.6-i*.28,stone);for(let i=0;i<5;i++)box(g,-.8+i*.38,.05,1.0,.3,.1,.3,stone);for(let i=0;i<4;i++)box(g,-.6+i*.4,.34,.45,.018,.25,.018,dark);return g;}
function bench(x,z,egypt){const g=new THREE.Group();g.position.set(x,0,z);group.add(g);box(g,0,.4,0,1.15,.1,.55);for(const xx of[-.45,.45])for(const zz of[-.2,.2])box(g,xx,.2,zz,.055,.4,.055);for(let i=0;i<3;i++){const handle=mesh(g,new THREE.CylinderGeometry(.018,.022,.29,7),wood,-.3+i*.3,.47,0);handle.rotation.z=Math.PI/2;const tool=mesh(g,egypt?new THREE.ConeGeometry(.03,.18,6):new THREE.IcosahedronGeometry(.07,1),egypt?copper:dark,-.15+i*.3,.47,0);tool.rotation.z=-Math.PI/2;}return g;}
function basket(g,x,y,z){mesh(g,new THREE.CylinderGeometry(.14,.1,.21,12,1,true),wood,x,y+.1,z);for(let k=0;k<4;k++){const ring=mesh(g,new THREE.TorusGeometry(.105+k*.009,.007,4,14),wood,x,y+.025+k*.055,z);ring.rotation.x=Math.PI/2;}}
function person(x,z){const g=new THREE.Group();g.position.set(x,0,z);group.add(g);const skin=new THREE.MeshStandardMaterial({color:0xa67854,roughness:.9});mesh(g,new THREE.SphereGeometry(.075,10,7),skin,0,.56,0);mesh(g,new THREE.CylinderGeometry(.09,.13,.31,9),cloth,0,.33,0);for(const xx of[-.055,.055])mesh(g,new THREE.CylinderGeometry(.025,.031,.2,6),skin,xx,.1,0);basket(g,0,.63,0);return g;}
if(level.id==='egypt'){
 quarry();bench(d+1.6,d+.7,true);const food=shelter(-d-1.5,d*.7);for(let i=0;i<4;i++){const loaf=mesh(food,new THREE.SphereGeometry(.075,10,6),new THREE.MeshStandardMaterial({color:0xcda46a,roughness:1}),-.3+i*.17,.1,.3);loaf.scale.y=.6;}
 sledge=new THREE.Group();group.add(sledge);sledge.position.set(-d-1.8,0,.3);for(const x of[-.28,.28])rope(sledge,[[x,.06,-.55],[x,.04,.45],[x,.15,.7]],.035);for(let i=0;i<4;i++)box(sledge,0,.12,-.38+i*.24,.65,.045,.19);box(sledge,0,.28,0,.48,.29,.48,stone);rope(sledge,[[-.25,.12,.65],[-.15,.08,1.1],[0,.12,1.55]],.015);
 const ramp=new THREE.Group();ramp.position.set(d+.8,0,-.8);group.add(ramp);for(let i=0;i<8;i++)box(ramp,0,(i+1)*.035,-i*.18,.72,(i+1)*.07,.19,earth);
}else if(level.id==='maya'){
 quarry();bench(d+1.5,d+.8,false);shelter(-d-1.5,d*.7);carrier=person(-d-1.4,.4);const bowl=mesh(group,new THREE.CylinderGeometry(.38,.28,.18,18,1,true),earth,d+1.2,.09,-.5);const plaster=mesh(group,new THREE.CircleGeometry(.32,24),cloth,d+1.2,.12,-.5);plaster.rotation.x=-Math.PI/2;for(let i=0;i<5;i++){const log=mesh(group,new THREE.CylinderGeometry(.05,.05,.65,7),wood,d+2+.1*i,.06,-1.5+.1*i);log.rotation.z=Math.PI/2;}const serpent=new THREE.Group();serpent.position.set(d+1.4,0,.2);group.add(serpent);box(serpent,0,.2,0,.44,.3,.65,stone);box(serpent,0,.13,.35,.48,.13,.42,stone);for(const x of[-.22,.22])mesh(serpent,new THREE.SphereGeometry(.035,8,5),dark,x,.3,.13);
}else{
 const pit=mesh(group,new THREE.CircleGeometry(.7,28),earth,-d-1.5,.002,-.3);pit.rotation.x=-Math.PI/2;for(let i=0;i<12;i++){const b=box(group,-d-2.3+(i%4)*.38,.07,d+.7+Math.floor(i/4)*.32,.32,.14,.27,earth);drying.push(b);}
 const molds=new THREE.Group();molds.position.set(d+1.6,0,d+.6);group.add(molds);for(let k=0;k<3;k++){const x=(k-1)*.44;for(const z of[-.2,.2])box(molds,x,.07,z,.4,.14,.035);for(const xx of[-.2,.2])box(molds,x+xx,.07,0,.035,.14,.4);}
 const kiln=mesh(group,new THREE.SphereGeometry(.55,20,10,0,Math.PI*2,0,Math.PI/2),earth,d+1.2,0,-d*.6);box(group,d+1.2,.18,-d*.6+.55,.25,.35,.015,dark);for(let i=0;i<7;i++)box(group,d+1.4+(i%3)*.29,.08+Math.floor(i/3)*.16,-d-.3,.25,.15,.25,new THREE.MeshStandardMaterial({color:0xb7704d,roughness:.88}));jar(group,d+1.3,.1,.9);mesh(group,new THREE.CircleGeometry(.13,16),dark,d+1.3,.34,.1).rotation.x=-Math.PI/2;carrier=person(-d-1.3,-.4);shelter(-d-1.5,d*.7);
}
const originalPositions=group.children.map(o=>({o,x:o.position.x}));return{setElevation(elevation){if(level.id!=='mesopotamia')return;for(const{o,x}of originalPositions)o.position.x=x+(elevation>0?Math.sign(x)*1.9:0);},animate(name){action=name;started=performance.now()*.001;},tick(time){const dt=time-started;if(action&&dt<6){if(sledge){const t=Math.sin(Math.min(dt/6,1)*Math.PI);sledge.position.x=-d-1.8+t*.6;sledge.position.z=.3+t*.3;}if(carrier)carrier.position.z=.4+Math.sin(dt*.65)*.65;if(drying.length&&action==='dry')for(let i=0;i<drying.length;i++)drying[i].scale.y=1+.06*Math.sin(dt+i);}else action=null;}};
}
