import {stoneArt, STONE_DETAILS} from './stone-art.js';
import {STONE_STYLES, GARDEN_SLOTS, studioLevel, redesignStudio, studioSnapshot, fillStudioLayer, decorateStudio} from './studio-game.js';
import {DECORATIONS, unlockDecoration} from './workshop-profile.js';

export function renderStudio({state, save, render, world, notice, confirm}) {
  const s=state.studio,profile=state.profile,root=document.getElementById('studio-controls'),level=studioLevel(s);
  const tabs=['design','build','decorate'];
  root.innerHTML=`<div class="studio-heading"><span class="eyebrow">FREE DESIGN WORKSHOP</span><h2>Make it yours.</h2><p>No orders. No time limit. Your stones are free.</p></div><div class="studio-tabs" role="group" aria-label="Workshop tools">${tabs.map(tab=>`<button data-studio-tab="${tab}" aria-pressed="${s.tab===tab}" class="${s.tab===tab?'selected':''}">${tab[0].toUpperCase()+tab.slice(1)}</button>`).join('')}</div>
    ${s.tab==='design'?`<section class="studio-section"><h3>How grand?</h3><div class="studio-options">${[3,5,7].map(n=>`<button data-studio-size="${n}" aria-pressed="${s.size===n}" class="${s.size===n?'selected':''}"><strong>${n} × ${n}</strong><small>${n===3?'Little wonder':n===5?'Grand pyramid':'Monumental'}</small></button>`).join('')}</div><h3>The silhouette</h3><div class="studio-options">${['smooth','stepped'].map(shape=>`<button data-studio-shape="${shape}" aria-pressed="${s.shape===shape}" class="${s.shape===shape?'selected':''}">${shape==='smooth'?'Smooth faces':'Stepped terraces'}</button>`).join('')}</div><h3>Your stone palette</h3><div class="stone-swatches">${Object.entries(STONE_STYLES).map(([id,style])=>`<button data-studio-style="${id}" aria-pressed="${s.stoneStyle===id}" class="${s.stoneStyle===id?'swatch-selected':''}"><span style="background:${style.color}"></span>${style.name}</button>`).join('')}</div><p class="studio-note">Size and silhouette create a new starting shape. Use Build to change individual stones, or Decorate to bring the grounds to life.</p></section>`:''}
    ${s.tab==='build'?`<section class="studio-section"><h3>Choose a layer <span>L${s.layer+1} active</span></h3><div class="studio-layers">${level.dims.map((n,i)=>`<button data-studio-layer="${i}" class="${i===s.layer?'selected':''}" aria-pressed="${i===s.layer}" aria-label="Build layer ${i+1}">L${i+1}<small>${n}×${n}</small></button>`).join('')}</div><div class="studio-pieces">${['brick','edge','corner','cap'].map(type=>`<button data-studio-part="${type}" class="${s.part===type&&s.tool==='place'?'studio-piece-selected':''}" aria-pressed="${s.part===type&&s.tool==='place'}">${stoneArt(type)}<strong>${STONE_DETAILS[type].label}</strong><small>Unlimited</small></button>`).join('')}</div><div class="studio-options"><button id="studio-place" class="${s.tool==='place'?'selected':''}">Place stone</button><button id="studio-lift" class="${s.tool==='remove'?'selected':''}">Lift out</button></div><button id="studio-fill" class="primary full">Fill the rest of L${s.layer+1}</button><p class="studio-note">Tap the worksite to build. Upper stones need support. The capstone belongs on L${s.size}.</p><button id="studio-clear" class="outline full">Clear stones & build from scratch</button></section>`:''}
    ${s.tab==='decorate'?`<section class="studio-section"><div class="studio-wallet"><strong>${profile.coins} earned coins</strong><span>Unlock once. Place as many as you like.</span></div><div class="decoration-catalog">${Object.entries(DECORATIONS).map(([id,d])=>{const owned=profile.decorations.includes(id);return `<button data-decoration="${id}" class="${s.decoration===id?'decor-selected':''}" aria-pressed="${s.decoration===id}" aria-label="${d.name}, ${owned?'owned':d.cost+' earned coins'}"><span class="decor-icon" aria-hidden="true">${d.symbol}</span><span><strong>${d.name}</strong><small>${d.description}</small></span><b>${owned?'✓':d.cost+' ◉'}</b></button>`;}).join('')}</div><p class="studio-note">Choose a decoration, then tap a gold space around the pyramid or choose a garden spot below.</p><div class="garden-map" aria-label="Garden decoration spots">${GARDEN_SLOTS.map((name,i)=>`<button data-garden="${i}" title="${name}" aria-label="${name}${s.decorations[i]?', '+DECORATIONS[s.decorations[i]].name:', empty'}"><span>${s.decorations[i]?DECORATIONS[s.decorations[i]].symbol:'+'}</span><small>${name}</small></button>`).join('')}</div><button id="studio-remove-decor" class="outline full ${s.decoration==='remove'?'selected':''}">Remove a decoration</button><p class="studio-note">Mission wages buy decorations. Replay a mission for practice; its wage is paid once.</p></section>`:''}
    <div class="studio-footer"><button id="studio-undo" class="outline" ${s.history.length?'':'disabled'}>Undo</button><span>Saved on this device</span></div>`;
  const change=(fn,landscape=false)=>{fn();save();render();if(landscape)world.landscape();else world.update();};
  const bind=(id,fn)=>{const b=root.querySelector('#'+id);if(b)b.onclick=fn;};
  root.querySelectorAll('[data-studio-tab]').forEach(b=>b.onclick=()=>change(()=>{s.tab=b.dataset.studioTab;s.tool=s.tab==='decorate'?'decorate':'place';}));
  const resize=(size,shape)=>{if(size===s.size&&shape===s.shape)return;confirm('Start with this shape?','This replaces the current stones. Your stone palette, unlocked decorations and garden layout stay with you.',()=>change(()=>redesignStudio(s,size,shape),true));};
  root.querySelectorAll('[data-studio-size]').forEach(b=>b.onclick=()=>resize(+b.dataset.studioSize,s.shape));
  root.querySelectorAll('[data-studio-shape]').forEach(b=>b.onclick=()=>resize(s.size,b.dataset.studioShape));
  root.querySelectorAll('[data-studio-style]').forEach(b=>b.onclick=()=>change(()=>{s.stoneStyle=b.dataset.studioStyle;}));
  root.querySelectorAll('[data-studio-layer]').forEach(b=>b.onclick=()=>change(()=>{s.layer=+b.dataset.studioLayer;}));
  root.querySelectorAll('[data-studio-part]').forEach(b=>b.onclick=()=>change(()=>{s.part=b.dataset.studioPart;s.tool='place';}));
  root.querySelectorAll('[data-decoration]').forEach(b=>b.onclick=()=>{
    const type=b.dataset.decoration;
    if(!profile.decorations.includes(type)&&!unlockDecoration(profile,type))return notice(`This decoration costs ${DECORATIONS[type].cost} earned coins. Complete a mission to earn more.`);
    change(()=>{s.decoration=type;s.tool='decorate';});
  });
  root.querySelectorAll('[data-garden]').forEach(b=>b.onclick=()=>change(()=>decorateStudio(s,profile,+b.dataset.garden)));
  bind('studio-place',()=>change(()=>{s.tool='place';}));bind('studio-lift',()=>change(()=>{s.tool='remove';}));
  bind('studio-fill',()=>{const message=fillStudioLayer(s);if(message)notice(message);else change(()=>{});});
  bind('studio-clear',()=>confirm('Clear your stones?','Your garden and unlocked decorations stay. You can undo this change.',()=>change(()=>{studioSnapshot(s);s.blocks=[];s.layer=0;s.tool='place';})));
  bind('studio-remove-decor',()=>change(()=>{s.decoration='remove';s.tool='decorate';}));
  bind('studio-undo',()=>change(()=>{const old=s.history.pop();if(old){s.blocks=old.blocks;s.decorations=old.decorations;}}));
}
