import {addForestEdge} from './forest-edge.js';
import {earthenRiseGeometry,risePathGeometry} from './earthen-rise.js';
import {shoreline,createRiverGeometry} from './river-geometry.js';
import {makeDeliveryBoat,addRiverbankDetails} from './riverside.js';
import {RenderReadiness} from './render-state.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {buildProps} from './site-props.js';
import {SoftwareRenderer} from './software-renderer.js';
import {LEVELS,COURSE,cells,key,target,bounds,previewTarget} from './game.js';
export function createWorld(container,getState,onPlace){
const readiness=new RenderReadiness();const manager=new THREE.LoadingManager();manager.onStart=()=>{readiness.loadStart();container.dataset.ready='loading';};manager.onLoad=()=>{readiness.loadDone();dirty=true;};manager.onError=url=>{container.dataset.assetError=url;};const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(58,1,.1,180);let renderer;try{renderer=new THREE.WebGLRenderer({antialias:true});}catch{renderer=new SoftwareRenderer();}
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.15;container.append(renderer.domElement);container.dataset.renderer=renderer instanceof SoftwareRenderer?'textured-software':'webgl-pbr';renderer.domElement.setAttribute('aria-label','3D building site. Drag to orbit, pinch or scroll to zoom.');const controls=new OrbitControls(camera,renderer.domElement);let dirty=true,lastFrame=0,frameSerial=0;controls.addEventListener('start',()=>{renderer.setInteractive?.(true);dirty=true;});controls.addEventListener('end',()=>{renderer.setInteractive?.(false);dirty=true;});controls.enableDamping=true;controls.enablePan=false;controls.minDistance=5;controls.maxDistance=25;controls.maxPolarAngle=Math.PI*.46;controls.target.set(0,.5,0);camera.position.set(4.35,4.65,4.95);
scene.add(new THREE.HemisphereLight(0xe6f6ff,0xa28a59,1.25));const sun=new THREE.DirectionalLight(0xfff3d2,4);sun.position.set(-6,11,7);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-15,right:15,top:15,bottom:-15});sun.shadow.bias=-.0002;sun.shadow.normalBias=.02;scene.add(sun);let env=new THREE.Group(),built=new THREE.Group(),grid=new THREE.Group();scene.add(env,built,grid);let rise,mound,flood,corridor,boat,contact,skyDome,sphinx,siteProps,boatStarted=0;let sphinxPromise;const gltfLoader=new GLTFLoader(manager);let guide=true;const loader=new THREE.TextureLoader(manager),textures=new Map();function texture(name,repeat=1,color=true){const k=name+repeat;if(!textures.has(k)){const t=loader.load('/textures/'+name+'.png');t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(repeat,repeat);if(color)t.colorSpace=THREE.SRGBColorSpace;t.anisotropy=8;textures.set(k,t);}return textures.get(k);}const pbrCache=new Map();function pbr(name,tint=0xffffff){const k=name+tint;if(!pbrCache.has(k))pbrCache.set(k,new THREE.MeshStandardMaterial({color:tint,map:texture(name+'-color'),normalMap:texture(name+'-normal-512',1,false),roughnessMap:texture(name+'-roughness',1,false),normalScale:new THREE.Vector2(.25,.25),roughness:.92}));return pbrCache.get(k);}const materials=new Map();const mat=(c)=>{if(!materials.has(c))materials.set(c,new THREE.MeshStandardMaterial({color:c,roughness:.8}));return materials.get(c);};
function mesh(parent,geo,color,x,y,z,shadow=true){const m=new THREE.Mesh(geo,mat(color));m.position.set(x,y,z);m.castShadow=shadow;m.receiveShadow=true;parent.add(m);return m;}
function box(p,x,y,z,w,h,d,c,r=.025){return mesh(p,new RoundedBoxGeometry(w,h,d,1,Math.min(r,h/4,w/4,d/4)),c,x,y,z);}
function dispose(g){for(const o of [...g.children]){g.remove(o);o.traverse(v=>{v.geometry?.dispose();if(v.userData.temporaryMaterial)v.material?.dispose();});}}
function ring(x0,x1,z0,z1,y,bevel=.018){const b=Math.min(bevel,(x1-x0)/3,(z1-z0)/3);return[[x0+b,y,z0],[x1-b,y,z0],[x1,y,z0+b],[x1,y,z1-b],[x1-b,y,z1],[x0+b,y,z1],[x0,y,z1-b],[x0,y,z0+b]];}
function stoneGeometry(b){if(b.type==='cap'){const g=new THREE.ConeGeometry(Math.SQRT1_2*.985,COURSE,4,1);g.rotateY(Math.PI/4);g.translate(0,COURSE/2,0);return g;}const q=bounds(b),x0=q.x0-b.x,x1=q.x1-b.x,z0=q.z0-b.z,z1=q.z1-b.z;const a=ring(-.492,.492,-.492,.492,.012,.035),mid=ring(x0+.008,x1-.008,z0+.008,z1-.008,COURSE-.025,.025),top=ring(x0+.027,x1-.027,z0+.027,z1-.027,COURSE-.006,.015);let pos=[];function tri(v1,v2,v3){pos.push(...v1,...v2,...v3);}for(const [lo,hi]of[[a,mid],[mid,top]])for(let i=0;i<8;i++){let j=(i+1)%8;tri(lo[i],hi[i],lo[j]);tri(lo[j],hi[i],hi[j]);}const centre=[(x0+x1)/2,COURSE-.006,(z0+z1)/2];for(let i=0;i<8;i++)tri(centre,top[(i+1)%8],top[i]);const geo=new THREE.BufferGeometry();geo.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));geo.computeVertexNormals();const uv=[];const normals=geo.attributes.normal;for(let i=0;i<pos.length/3;i++){const x=pos[i*3],y=pos[i*3+1],z=pos[i*3+2],nx=Math.abs(normals.getX(i)),ny=Math.abs(normals.getY(i)),nz=Math.abs(normals.getZ(i));uv.push(ny>nx&&ny>nz?x*4:(nx>nz?z*4:x*4),ny>nx&&ny>nz?z*4:y*4);}geo.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));return geo;}
function addPart(b,preview=false){const group=new THREE.Group();group.position.set(b.x,b.y*COURSE,b.z);if(b.type==='stairs'&&(b.routeId==='rear'||b.side==='rear'))group.rotation.y=Math.PI;if(!preview)group.userData.block=b;built.add(group);const l=LEVELS[getState().level];const variation=((b.x*7+b.z*11+b.y*3)%5)*.012;const c=new THREE.Color(l.color).offsetHSL(0,variation,variation);if(['brick','edge','corner','cap'].includes(b.type)){const m=mesh(group,stoneGeometry(b),c.getHex(),0,0,0);m.userData.block=b;}else if(b.type==='stairs'){const run=l.id==='maya'?.5:1;for(let i=0;i<5;i++)box(group,0,(i+1)*COURSE/10,run*(.4-i*.18),.94,(i+1)*COURSE/5,run*.185,l.color,.012);}else{box(group,0,.35,0,.96,.7,.96,l.color,.035);box(group,0,.76,0,1.08,.16,1.06,l.id==='maya'?0xc6b894:0xb97957,.028);box(group,0,.99,-.28,.8,.32,.2,l.id==='maya'?0xcdbf9d:0x8d563d,.025);box(group,0,.28,.485,.31,.5,.025,0x423d32,.004);for(const x of[-.37,.37])box(group,x,.37,.495,.1,.66,.11,l.id==='maya'?0xf1e6c7:0xd3a176,.014);}
 group.traverse(m=>{if(m.isMesh){if(m.material.color.getHex()!==0x423d32)m.material=pbr(l.id==='mesopotamia'?'earth':'limestone',b.material==='core'?0xcac3b0:0xffffff);if(!preview)m.userData.block=b;else delete m.userData.block;if(preview){m.material=m.material.clone();m.material.map=null;m.material.normalMap=null;m.material.roughnessMap=null;m.material.color.set(0x3e9ba8);m.material.transparent=true;m.material.opacity=.10;m.material.depthWrite=false;m.castShadow=false;m.userData.temporaryMaterial=true;}}});}
const movingFronds=[];let waterMaterial,waterGeo;
function tree(x,z,jungle,height=2.8){const trunkCurve=new THREE.CatmullRomCurve3([new THREE.Vector3(x,0,z),new THREE.Vector3(x+.07,height*.45,z+.06),new THREE.Vector3(x+.16,height,z)]);const trunk=mesh(env,new THREE.TubeGeometry(trunkCurve,9,.105,10,false),0xffffff,0,0,0);trunk.material=new THREE.MeshStandardMaterial({map:texture('palm-bark-color'),normalMap:texture('palm-bark-normal',1,false),roughness:1});const crown=new THREE.Vector3(x+.16,height,z);
 if(!jungle){const leafMap=texture('palm-frond-alpha');leafMap.wrapS=leafMap.wrapT=THREE.ClampToEdgeWrapping;const leafMat=new THREE.MeshStandardMaterial({map:leafMap,color:0xe7f3cc,alphaTest:.25,alphaToCoverage:true,side:THREE.DoubleSide,roughness:.8});for(let j=0;j<12;j++){const angle=j*Math.PI*2/12+.21*(j%3),length=1.45+(j%4)*.13,droop=.65+(j%3)*.2;const pos=[],uv=[],indices=[];for(let i=0;i<=12;i++){const t=i/12,rad=length*t,yy=Math.sin(t*Math.PI)*.3-droop*t*t;for(const side of[-1,1]){const spread=.33*side;pos.push(Math.sin(angle)*rad+Math.cos(angle)*spread,yy,Math.cos(angle)*rad-Math.sin(angle)*spread);uv.push(t,(side+1)/2);}}for(let i=0;i<12;i++){const a=i*2;indices.push(a,a+1,a+2,a+1,a+3,a+2);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(indices);g.computeVertexNormals();const frond=new THREE.Mesh(g,leafMat);frond.position.copy(crown);frond.castShadow=true;env.add(frond);movingFronds.push({mesh:frond,phase:j*.7+x});}}
 else{const leafMap=texture('jungle-leaf-alpha');leafMap.wrapS=leafMap.wrapT=THREE.ClampToEdgeWrapping;const leafMat=new THREE.MeshStandardMaterial({map:leafMap,color:0xbedca8,alphaTest:.25,alphaToCoverage:true,side:THREE.DoubleSide,roughness:.85});for(let j=0;j<28;j++){const angle=j*2.399,r=.45+((j*7)%11)/11*.8;const leaf=new THREE.Mesh(new THREE.PlaneGeometry(.75,.95),leafMat);leaf.position.set(crown.x+Math.cos(angle)*r,crown.y+Math.sin(j*1.7)*.6,crown.z+Math.sin(angle)*r);leaf.rotation.set(-.4+Math.sin(j)*.65,angle,.2*Math.cos(j));leaf.castShadow=true;env.add(leaf);}}
}
const shore=shoreline;
function river(){const surfaces=createRiverGeometry();waterGeo=surfaces.water;waterMaterial=new THREE.MeshStandardMaterial({color:0x426875,map:texture('water-color',1),normalMap:texture('water-normal-512',2,false),normalScale:new THREE.Vector2(.2,.2),roughness:.19,metalness:.35,vertexColors:true,transparent:true,opacity:1,depthWrite:false,fog:false,side:THREE.DoubleSide});const water=new THREE.Mesh(waterGeo,waterMaterial);water.userData.water=true;env.add(water);const material=pbr('sand',0xeee4c9).clone();material.vertexColors=true;material.transparent=true;material.side=THREE.DoubleSide;const bank=new THREE.Mesh(surfaces.banks,material);bank.userData.bank=true;env.add(bank);}
function landscape(){readiness.beginScene();container.dataset.ready='loading';dirty=true;dispose(env);movingFronds.length=0;contact=null;sphinx=null;siteProps=null;mound=null;rise=null;flood=null;corridor=null;boat=null;const l=LEVELS[getState().level];const n=l.dims[0];camera.position.set(n*1.56,n*.65,n*1.75);controls.target.set(0,.55,0);controls.update();scene.background=new THREE.Color(l.sky);scene.userData.groundColor='#'+new THREE.Color(l.ground).getHexString();scene.fog=new THREE.Fog(l.sky,22,55);const sceneMap=l.id+'-environment';if(sceneMap){const pano=texture(sceneMap);pano.wrapS=THREE.RepeatWrapping;pano.wrapT=THREE.ClampToEdgeWrapping;pano.repeat.set(1,1);pano.offset.set(l.id==='egypt'?.47:0,0);skyDome=new THREE.Mesh(new THREE.SphereGeometry(70,64,32),new THREE.MeshBasicMaterial({map:pano,side:THREE.DoubleSide}));skyDome.position.copy(camera.position);skyDome.userData.background=true;scene.userData.environmentTexture=pano;env.add(skyDome);pano.mapping=THREE.EquirectangularReflectionMapping;scene.environment=pano;scene.environmentIntensity=.55;}else skyDome=null;
const edgeCanvas=document.createElement('canvas');edgeCanvas.width=edgeCanvas.height=256;const ec=edgeCanvas.getContext('2d');const grad=ec.createRadialGradient(128,128,62,128,128,126);grad.addColorStop(0,'white');grad.addColorStop(1,'black');ec.fillStyle=grad;ec.fillRect(0,0,256,256);const ground=mesh(env,new THREE.PlaneGeometry(22,22,22,22),0xffffff,0,-.055,0,false);ground.rotation.x=-Math.PI/2;ground.material=pbr(l.id==='maya'?'limestone':l.id==='egypt'?'sand':'earth',0xffffff).clone();ground.material.map=texture((l.id==='maya'?'limestone':l.id==='egypt'?'sand':'earth')+'-color',4);if(sceneMap){ground.material.alphaMap=new THREE.CanvasTexture(edgeCanvas);ground.material.transparent=true;}ground.userData.ground=true;
const plot=box(env,0,-.015,0,l.dims[0]+2.3,.06,l.dims[0]+2.3,l.id==='maya'?0xc7bea0:0xe6d0a1,.015);plot.userData.ground=true;plot.material=pbr(l.id==='maya'?'limestone':'sand',0xf9f3e3);mound=plot;if(l.site){rise=new THREE.Group();const soil=new THREE.Mesh(earthenRiseGeometry(l.dims[0]+2.3),pbr('earth',0xf2e5cd).clone());soil.material.side=THREE.DoubleSide;soil.material.vertexColors=true;soil.material.transparent=true;rise.add(soil);const path=new THREE.Mesh(risePathGeometry(l.dims[0]+2.3),pbr('sand',0xc9b98e));rise.add(path);env.add(rise);}const shadowCanvas=document.createElement('canvas');shadowCanvas.width=shadowCanvas.height=256;const sh=shadowCanvas.getContext('2d');sh.shadowColor='rgba(45,35,20,.55)';sh.shadowBlur=24;sh.fillStyle='rgba(45,35,20,.25)';sh.fillRect(40,40,176,176);contact=new THREE.Mesh(new THREE.PlaneGeometry(l.dims[0]+1.65,l.dims[0]+1.65),new THREE.MeshBasicMaterial({map:new THREE.CanvasTexture(shadowCanvas),transparent:true,opacity:.85,depthWrite:false}));contact.rotation.x=-Math.PI/2;contact.position.y=.027;env.add(contact);if(l.site){flood=mesh(env,new THREE.PlaneGeometry(14,14),0x4ca5bd,0,COURSE,0,false);flood.rotation.x=-Math.PI/2;flood.material=new THREE.MeshStandardMaterial({map:texture('water-color'),color:0x8ac7d4,transparent:true,opacity:.62,side:THREE.DoubleSide});flood.visible=false;}if(l.siteConstraints){corridor=mesh(env,new THREE.PlaneGeometry(8,.6),0xb5bda0,0,.026,2.35,false);corridor.rotation.x=-Math.PI/2;corridor.material=pbr('earth',0xd9e1c5);const pool=mesh(env,new THREE.CircleGeometry(1.0,48),0x277985,5,.003,2.35,false);pool.rotation.x=-Math.PI/2;pool.material=new THREE.MeshStandardMaterial({map:texture('water-color'),normalMap:texture('water-normal-512',2,false),color:0x6aa5a5,roughness:.3});for(let a=0;a<16;a++){const rock=mesh(env,new THREE.IcosahedronGeometry(.18,1),0xa8b294,5+Math.cos(a*Math.PI/8)*1.05,.05,2.35+Math.sin(a*Math.PI/8)*1.05);rock.scale.y=.55;}}
 // Survey posts and prepared material yard belong to the active, cleared site.
 for(const x of[-1,1])for(const z of[-1,1]){const xx=x*(l.dims[0]/2+1.25),zz=z*(l.dims[0]/2+1.25);mesh(env,new THREE.CylinderGeometry(.045,.055,.5,8),0x826b47,xx,.23,zz);const peg=mesh(env,new THREE.SphereGeometry(.07,8,6),0xc69b50,xx,.5,zz);}
 for(let i=0;i<8;i++){const b=box(env,-4+(i%2)*.58,.17+Math.floor(i/4)*.3,-.7+Math.floor(i%4/2)*.52,.53,.29,.48,l.color,.045);b.material=pbr(l.id==='mesopotamia'?'earth':'limestone');}
 for(let i=0;i<34;i++){const a=i*2.4,r=5+(i%4)*.6,x=Math.cos(a)*r,z=Math.sin(a)*r;const rock=mesh(env,new THREE.IcosahedronGeometry(.09+(i%3)*.03,0),l.id==='maya'?0x8f9980:0xc2ac80,x,.045,z);rock.scale.y=.55;}
 if(l.id==='egypt'){river();addRiverbankDetails(env,shore,pbr);for(const [z,h,dx]of[[-10,2.6,.6],[-8.2,2.1,1.4],[-6.7,2.8,.45],[5.8,2.1,.7],[8.7,2.7,1.2]])tree(shore(z)+dx,z,false,h);boat=makeDeliveryBoat();boat.userData.skipGroundShadow=true;env.add(boat);boat.position.set(shore(-5)-1,0,-5);}
 if(l.id==='maya'){movingFronds.push(...addForestEdge(env,texture));}
 if(l.id==='mesopotamia'){for(let i=0;i<5;i++){const x=3+(i%3)*1.5,z=-6-Math.floor(i/3)*1.4;box(env,x,.4,z,1.25,.8,1.15,0xb48b66,.06);box(env,x,.83,z,1.3,.12,1.2,0xd3ad81,.015);box(env,x,.25,z+.58,.25,.5,.025,0x766049,.005);}for(let i=0;i<18;i++)mesh(env,new THREE.ConeGeometry(.06,.55,5),0x879457,-6.7+(i%2)*.2,.23,-5+i*.45);}
 siteProps=buildProps(env,l,{stone:pbr('limestone'),earth:pbr('earth')});
 if(l.id==='egypt'){if(!sphinxPromise)sphinxPromise=gltfLoader.loadAsync('/models/sphinx.glb');sphinxPromise.then(asset=>{if(LEVELS[getState().level].id!=='egypt')return;sphinx=asset.scene.clone(true);sphinx.scale.setScalar(.23);sphinx.position.set(-3,.02,-10);sphinx.rotation.y=-.3;sphinx.traverse(m=>{if(m.isMesh){m.castShadow=true;m.receiveShadow=true;m.material=m.material.clone();}});sphinx.visible=!!getState().laterGiza;env.add(sphinx);dirty=true;}).catch(()=>{});}
 update();}
function update(){dirty=true;dispose(built);dispose(grid);const s=getState(),l=LEVELS[s.level],elevation=l.site&&s.siteChoice==='high'?COURSE*2:0;built.position.y=grid.position.y=elevation;built.userData.shadowReceiverY=elevation+.018;const shadowHalf=(l.dims[0]+2.3)/2;built.userData.shadowBounds={minX:-shadowHalf,maxX:shadowHalf,minZ:-shadowHalf,maxZ:shadowHalf};if(mound){mound.position.y=elevation-.015;mound.scale.y=1;}if(rise){rise.visible=elevation>0;rise.scale.y=elevation;}siteProps?.setElevation?.(elevation);if(contact)contact.position.y=elevation+.027;if(sphinx)sphinx.visible=!!s.laterGiza;if(flood)flood.visible=!!s.waterPreview;const plan=['plan','shop'].includes(s.stage);if(plan){for(const b of s.blocks)if(!(s.cutaway&&b.z>0&&!b.stair))addPart(b);for(const b of previewTarget(l,s))if(!s.blocks.some(p=>key(p.x,p.y,p.z)===key(b.x,b.y,b.z))&&!(s.cutaway&&b.z>0&&!b.stair))addPart(b,true);}else{for(const b of s.blocks)if(!(s.cutaway&&b.z>0&&!b.stair))addPart(b);if(guide)for(const b of target(l)){if(s.blocks.some(p=>key(p.x,p.y,p.z)===key(b.x,b.y,b.z))||(s.cutaway&&b.z>0&&!b.stair))continue;addPart(b,true);}if(s.stage==='complete')return;const n=l.dims[s.layer]+2;const gridCells=cells(n,s.layer).filter(b=>!s.blocks.some(p=>key(p.x,p.y,p.z)===key(b.x,b.y,b.z))&&(s.layer===0||target(l).some(p=>key(p.x,p.y,p.z)===key(b.x,b.y,b.z))));for(const stair of target(l).filter(b=>b.stair&&b.y===s.layer)){if(!gridCells.some(b=>key(b.x,b.y,b.z)===key(stair.x,stair.y,stair.z)))gridCells.push(stair);else{const c=gridCells.find(b=>key(b.x,b.y,b.z)===key(stair.x,stair.y,stair.z));c.stair=true;}};for(const b of gridCells){const m=mesh(grid,new THREE.PlaneGeometry(.92,.92),0x418fad,b.x,b.y*COURSE+.014,b.z,false);m.rotation.x=-Math.PI/2;m.material=m.material.clone();m.material.transparent=true;m.material.opacity=.14;m.material.depthWrite=false;m.userData.temporaryMaterial=true;m.userData.cell=b;}}}
function resize(){dirty=true;camera.aspect=container.clientWidth/container.clientHeight;camera.updateProjectionMatrix();renderer.setSize(container.clientWidth,container.clientHeight);}new ResizeObserver(resize).observe(container);const ray=new THREE.Raycaster(),v=new THREE.Vector2();let down=null;const pointers=new Set();renderer.domElement.addEventListener('pointerdown',e=>{pointers.add(e.pointerId);down=pointers.size===1?{x:e.clientX,y:e.clientY}:null;});renderer.domElement.addEventListener('pointercancel',e=>{pointers.delete(e.pointerId);down=null;});renderer.domElement.addEventListener('pointerup',e=>{const multi=pointers.size>1;pointers.delete(e.pointerId);if(multi){down=null;return;}if(!down||Math.hypot(e.clientX-down.x,e.clientY-down.y)>7||!['build','complete'].includes(getState().stage))return;down=null;const r=renderer.domElement.getBoundingClientRect();v.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(v,camera);const hit=getState().tool==='remove'?ray.intersectObjects(built.children,true).find(h=>h.object.userData.block):ray.intersectObjects(grid.children)[0];if(hit){const b=hit.object.userData.block||hit.object.userData.cell;onPlace(b.x,b.y,b.z,b.stair);}});
renderer.setAnimationLoop(()=>{const time=performance.now()*.001;const changed=controls.update();if(skyDome)skyDome.position.copy(camera.position);if(renderer instanceof SoftwareRenderer&&!dirty&&!changed&&time-lastFrame<.7)return;dirty=false;lastFrame=time;siteProps?.tick(time);for(const f of movingFronds)f.mesh.rotation.z=Math.sin(time*.6+f.phase)*.018;if(boat&&boatStarted){const d=Math.min(10,time-boatStarted);boat.position.z=-5+(d<=5?d:10-d)*.8;boat.position.x=shore(boat.position.z)-1;for(const cargo of boat.children.filter(c=>c.userData.cargo))cargo.visible=d<5;}if(waterMaterial){waterMaterial.map.offset.y=time*.018;waterMaterial.normalMap.offset.x=time*.024;}renderer.render(scene,camera);container.dataset.frame=String(++frameSerial);if(readiness.frameDone())container.dataset.ready='ready';container.dataset.frameMs=String(Math.round(renderer.lastRenderMs||0));container.dataset.shadowMs=String(Math.round((renderer.lastShadowMs||0)*100)/100);container.dataset.shadowCacheHits=String(renderer.shadowCache?.hits||0);container.dataset.shadowCacheMisses=String(renderer.shadowCache?.misses||0);});resize();landscape();return{update,landscape,followBoat(){if(!boat)return;boatStarted=performance.now()*.001;boat.position.set(shore(-5)-1,0,-5);controls.target.copy(boat.position).add(new THREE.Vector3(0,.3,0));camera.position.copy(boat.position).add(new THREE.Vector3(3,2,3));controls.update();dirty=true;},animateWork(name){siteProps?.animate(name);dirty=true;},animateDelivery(load){boatStarted=performance.now()*.001;if(boat){for(const o of [...boat.children].filter(o=>o.userData.cargo))boat.remove(o);let i=0;for(const[t,n]of Object.entries(load||{}))for(let k=0;k<n;k++){const cargo=mesh(boat,t==='cap'?new THREE.ConeGeometry(.16,.25,4):new THREE.BoxGeometry(.24,.2,.24),0xecd8ae,(i%2-.5)*.24,.25,-.3+Math.floor(i/2)*.28);cargo.userData.cargo=true;i++;}}},toggleGuide(){guide=!guide;update();return guide;},rotate(){const p=camera.position.clone().sub(controls.target);p.applyAxisAngle(new THREE.Vector3(0,1,0),Math.PI/4);camera.position.copy(controls.target).add(p);controls.update();},zoom(f){camera.position.sub(controls.target).multiplyScalar(f).add(controls.target);controls.update();},home(){const n=LEVELS[getState().level].dims[0];camera.position.set(n*1.56,n*.65,n*1.75);controls.target.set(0,.5,0);controls.update();}};
}
