import test from'node:test';import assert from'node:assert/strict';import{SCENES,LEVELS,COURSE,target,quantities,supported,validate,initial,required,sku,planningValid,available}from'../game.js';
test('Three scenes own four ordered missions each',()=>{assert.equal(SCENES.length,3);assert.equal(LEVELS.length,12);for(const s of SCENES)assert.equal(LEVELS.filter(l=>l.id===s.id).length,4);});
test('Egypt14 pieces preserve accepted centred maths and real shapes',()=>assert.deepEqual(quantities(LEVELS[0]),{brick:1,edge:4,corner:8,cap:1}));
for(const l of LEVELS){test(`${l.missionId}: final shape and route support`,()=>{assert.deepEqual(validate(l,target(l)),{missing:0,extra:0,wrong:0,unsupported:0});});test(`${l.missionId}: seeded inventory and budget`,()=>{const s=initial(LEVELS.indexOf(l));assert.equal(s.blocks.length,l.seed.length);assert.ok(l.minimumTotalCost<=l.budget);for(const b of l.seed.filter(b=>b.locked))assert.ok(target(l).some(t=>t.x===b.x&&t.y===b.y&&t.z===b.z&&sku(t)===sku(b)));assert.deepEqual(Object.fromEntries(Object.entries(required(l)).filter(([,n])=>n)),l.requiredNewQuantities);});test(`${l.missionId}: locked progression is scene-local`,()=>{assert.equal(available(l,[]),!l.unlocksAfter);if(l.unlocksAfter)assert.ok(available(l,[l.unlocksAfter]));});}
test('Rear stair cannot be supported by front stair',()=>{const l=LEVELS[5],b={x:0,y:1,z:-1.75,type:'stairs',routeId:'rear'};assert.equal(supported(b,[{x:0,y:0,z:2.25,type:'stairs',routeId:'front'}],l),false);});
test('Repair route starts disconnected and can move without buying',()=>{const l=LEVELS[6],s=initial(6);assert.ok(validate(l,s.blocks).extra);assert.ok(validate(l,s.blocks).missing);assert.equal(l.minimumPurchaseCost,0);assert.deepEqual(required(l),{brick:0,temple:0,stairs:0});});
test('Ur core/facing quantities and correct-material check',()=>{const l=LEVELS[11];assert.deepEqual(quantities(l),{core:10,facing:24,temple:1,stairs:2});const wrong=structuredClone(target(l));wrong.find(b=>b.material==='facing').material='core';assert.equal(validate(l,wrong).wrong,1);});
test('Flood choice checks elevation, not a timer',()=>{const l=LEVELS[10],s=initial(10);assert.equal(planningValid(l,s),false);s.siteChoice='low';assert.equal(planningValid(l,s),false);s.siteChoice='high';assert.equal(planningValid(l,s),true);});
test('All source-defined mission minimums are exact',()=>assert.deepEqual(LEVELS.map(l=>l.minimumTotalCost),[21,21,13,51,19,17,0,40,27,28,30,74]));
